name: image_picker_for_web
description: Web platform implementation of image_picker
publish_to: 'none'
version: 2.1.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: image_picker
    platforms:
      web:
        pluginClass: ImagePickerPlugin
        fileName: image_picker_for_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image_picker_platform_interface: 
    git:
      url: https://github.com/Hacker437/ImagePicker.git
      path: image_picker_platform_interface
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
